### PR TITLE
[PI-1925] Give CA the ability to scan pods only in a namespace.

### PR DESCRIPTION
**Pull request by yushenli**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Luke-Smartnews — CHANGES_REQUESTED** [review]
we agreed to use sn-master branch, right?

**Comment by yushenli** [comment]
> we agreed to use sn-master branch, right?

Yes, but you haven't fast forwarded sn-master to cluster-autoscaler-release-1.25 yet. So if I choose sn-master as the base, this PR will include all your previous 5 commits.

**Comment by Luke-Smartnews** [comment]
> if I choose sn-master as the base, this PR will include all your previous 5 commits.

no, I cloned the sn-master from cluster-autoscaler-release-1.25 .

**Review by Luke-Smartnews — APPROVED** [review]

**Comment by yushenli** [comment]
> > if I choose sn-master as the base, this PR will include all your previous 5 commits.
> 
> no, I cloned the sn-master from cluster-autoscaler-release-1.25 .

As discussed in https://smartnews.slack.com/archives/G01LJC21NTF/p1670216943571189
I recreated branch `sn-master`, and now it's synced to the HEAD@cluster-autoscaler-release-1.25

**Pull request merged**
